config/routes.rb
Rails.application.routes.draw do
  root to: 'problems#index'
  resources :steps
  resources :problems
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem.rb
class Problem < ApplicationRecord
  has_many :steps, dependent: :destroy
  validates :title, presence: true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :problem
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  def index
    @problems = Problem.all
  end

  def show; end

  def new
    @problem = Problem.new
  end

  def edit; end

  def create
    @problem = Problem.new(problem_params)

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html { render :new }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_problem
      @problem = Problem.find(params[:id])
    end

    def problem_params
      params.require(:problem).permit(:title)
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  def index
    @steps = Step.all
  end

  def show; end

  def new
    @step = Step.new
  end

  def edit; end

  def create
    @step = Step.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step.problem, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step.problem, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to @step.problem, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_step
      @step = Step.find(params[:id])
    end

    def step_params
      params.require(:step).permit(:title, :problem_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ProblemsWithSteps
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield

app/views/problems/_form.html.haml
= form_with(model: problem, local: true) do |form|
  - if problem.errors.any?
    #error_explanation
      %h2
        = pluralize(problem.errors.count, "error")
        prohibited this problem from being saved:
      %ul
        - problem.errors.full_messages.each do |message|
          %li= message
  .actions
    .form-group
      = form.text_field :title, placeholder: true, class: 'form-control'
    .form-group
      = form.submit

app/views/problems/edit.html.haml
%h1 Editing Problem
= render 'form', problem: @problem
= link_to 'Show', @problem
|
\#{link_to 'Back', problems_path}

app/views/problems/index.html.haml
%p#notice= notice
%h1 Problems
%table
  %thead
    %tr
      %th{:colspan => "4"}
  %tbody
    - @problems.each do |problem|
      %tr
        %td= problem.title
        %td= link_to 'Show', problem
        %td= link_to 'Edit', edit_problem_path(problem)
        %td= link_to 'Destroy', problem, method: :delete, remote: true
%br/
= link_to 'New Problem', new_problem_path

app/views/problems/new.html.haml
%h1 New Problem
= render 'form', problem: @problem
= link_to 'Back', problems_path

app/views/problems/show.html.haml
%p#notice= notice
%h2
  = @problem.title
%br
  = link_to 'New Step', new_step_path(problem: @problem.id)
  - @problem.steps.each do |step|
    %h3
      = link_to step.title, edit_step_path(step.id)
      = link_to 'Destroy', step, method: :delete, remote: true
= link_to 'Edit', edit_problem_path(@problem)
|
#{link_to 'Back', problems_path}

app/views/steps/_form.html.haml
= form_with(model: step, local: true) do |form|
  - if step.errors.any?
    #error_explanation
      %h2
        = pluralize(step.errors.count, "error")
        prohibited this step from being saved:
      %ul
        - step.errors.full_messages.each do |message|
          %li= message
  .actions
    .form-group
      = form.text_field :title, placeholder: true, class: 'form-control'
      = form.hidden_field :problem_id, value: problem, class: 'form-control'
    .form-group
      = form.submit

app/views/steps/edit.html.haml
%h1 Editing Step
= render 'form', step: @step, problem: @step.problem.id
= link_to 'Show', @step
|
#{link_to 'Back', problem_path(@step.problem.id)}

app/views/steps/index.html.haml
%p#notice= notice
%h1 Steps
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @steps.each do |step|
      %tr
        %td= link_to 'Show', step
        %td= link_to 'Edit', edit_step_path(step)
        %td= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Step', new_step_path

app/views/steps/new.html.haml
%h1 New Step
= render 'form', step: @step, problem: params[:problem]
= link_to 'Back', steps_path

app/views/steps/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_step_path(@step)
|
#{link_to 'Back', problem_path(@step.problem.id)}